CatalogPage and inner components
selivanov-d/thinknetica-react-basic pull request #3
Opened 2018-11-10 07:12 UTC by selivanov-d

2018-11-10 12:01 UTC, index01d requested changes

2018-11-10 12:01 UTC, index01d commented on src/components/CatalogItems.js
> +                  title={product.title}
лучше передать продукт целиком, деструктурировать уже в  карточке, тогда код каталога будет чище

2018-11-10 12:01 UTC, index01d commented on src/components/CatalogPage.js
> +    <div className="page -catalog">
пробел лишний?

2018-11-10 12:01 UTC, index01d commented on src/components/Image.js
> +  if (typeof src !== 'string') return null;
не забудь в следующем занятии обратить внимание на propTypes

2018-11-10 12:01 UTC, index01d commented on src/components/ProductCardImage.js
> +const ProductCardImage = ({imageUrl = '//via.placeholder.com/320x240', imageAlt, width = 320, height = 240}) => {
можно было бы оставить названия свойств src, alt, чтобы не создавать разнообразия

2018-11-10 12:01 UTC, index01d commented on src/components/ProductCardImage.js
> +import React from 'react';
составные части карточки продукта лучше сложить в директорию `components/ProductCard`, тогда можно будет избежать избыточности в названии модуля

2018-11-10 12:01 UTC, index01d commented on src/components/ProductCardImage.js
> +import React from 'react';
саму карточку положить в эту же директорию

2018-11-10 12:01 UTC, index01d commented on src/components/Image.js
> +  if (typeof src !== 'string') return null;
сейчас можно не править

2018-11-11 05:39 UTC, selivanov-d commented on src/components/CatalogPage.js
> +    <div className="page -catalog">
Нет. :)
В компании где я работаю принята такая нотация, которая является несколько упрощённой копией БЭМ:
```
.block
.block_element
.block_element.-modifier
```

Соответственно, `-catalog` это Модификатор. В Sass-листах стилей они пишутся так:
```
.block_element
 &.-modifier
    // some rules
```

В объявлении Модификатора обязательно используется амперсанд, чтобы он (Модификатор) работал только с тем элементом, который он модифицирует и нигде более.

Но сейчас он действительно не нужен. Убрал.

2018-11-11 05:40 UTC, selivanov-d commented on src/components/Image.js
> +  if (typeof src !== 'string') return null;
👌

2018-11-11 05:47 UTC, selivanov-d commented on src/components/CatalogItems.js
> +                  title={product.title}
Действительно. :)
Поправил.

2018-11-11 05:50 UTC, selivanov-d commented on src/components/ProductCardImage.js
> +const ProductCardImage = ({imageUrl = '//via.placeholder.com/320x240', imageAlt, width = 320, height = 240}) => {
Поправил.

2018-11-11 06:16 UTC, selivanov-d commented on src/components/ProductCardImage.js
> +import React from 'react';
Переколбасил структуру каталогов. Не уверен, что получил хороший результат. Может быть ещё раз переделаю.

2018-11-12 07:33 UTC, index01d commented on src/components/ProductCardImage.js
> +import React from 'react';
когда объединяешь в карточку, то можно уже называть не CardImage, а просто Image.
Из практики: лучше держать стили рядом с компонентом в одной директории (заодно не будет доп каталога в пути js/)

2018-11-12 07:34 UTC, index01d commented on src/components/CatalogPage.js
> +    <div className="page -catalog">
если это конвенция то ок:) я не против

2018-11-12 07:35 UTC, index01d approved these changes

2018-11-14 17:16 UTC, merged