Pages Contacts, 404, Catalog, Cart and corresponding routes
selivanov-d/thinknetica-react-basic pull request #5
Opened 2018-11-23 10:38 UTC by selivanov-d

2018-11-24 06:22 UTC, index01d requested changes

2018-11-24 06:22 UTC, index01d commented on src/js/components/App.js
> +          <Navbar color="light" light expand="md">
меню стоит сразу декомпозировать в отдельный компонент

2018-11-24 06:22 UTC, index01d commented on src/js/components/App.js
> +    cart: [],
следует вынести состояние корзины и все методы для работы с ней в отдельный компонент-контейнер

2018-11-24 06:22 UTC, index01d commented on src/js/components/App.js
> +    cart: [],
в инициализирующем коде не должно быть бизнес-логики

2018-11-24 06:22 UTC, index01d commented on src/js/components/ProductCard/ProductCard.js
> +            <Link to={`/product/${id}`}>{title}</Link>
почему не pathHelper?

2018-11-24 06:22 UTC, index01d commented on src/js/pages/IndexPage.js
> +      history.replace(indexPagePath(), {});
а зачем history.replace?

2018-11-24 06:22 UTC, index01d commented on src/js/pages/IndexPage.js
> +      this.setState({ alert });
если можно обойтись без использования состояния и посчитать необходимое в render, то это было бы лучшим вариантом

2018-11-25 14:37 UTC, selivanov-d commented on src/js/components/ProductCard/ProductCard.js
> +            <Link to={`/product/${id}`}>{title}</Link>
Упустил. :(
Поправил.

2018-11-25 14:52 UTC, selivanov-d commented on src/js/pages/IndexPage.js
> +      history.replace(indexPagePath(), {});
Мне нужно показать сообщение о редиректе только один раз -- сразу после того, как я был перенаправлен на главную страницу со страницы пустой корзины. 

Чтобы сделать это, я удаляю сообщение о редиректе из `this.props.history` после загрузки компонента `IndexPage` после редиректа. Если сообщение оставить в  `this.props.history.location.state.redirectReason`, то оно будет показано каждый раз как я перезагружаю страницу.

2018-11-25 14:57 UTC, selivanov-d commented on src/js/pages/IndexPage.js
> +      this.setState({ alert });
Мне тоже кажется, что моё решение не идеально. Но я не знаю как сделать однократный показ сообщения лучше. Сохранение сообщения в state позволяет мне очистить `this.props.history.location.state.redirectReason`, но, при этом, показывать сообщение о редиректе из пустой корзины.

2018-11-25 15:19 UTC, selivanov-d commented on src/js/components/App.js
> +          <Navbar color="light" light expand="md">
Сделал.

2018-11-25 16:18 UTC, selivanov-d commented on src/js/components/App.js
> +    cart: [],
Вынес всё в CartContainer.

2018-11-26 11:37 UTC, index01d commented on src/js/pages/IndexPage.js
> +      history.replace(indexPagePath(), {});
с replace будет лишняя перерисовка, лучше зачистить состояние в history.listen

2018-11-26 11:38 UTC, index01d approved these changes

2018-11-27 18:43 UTC, merged