API middleware, prepareData helper, cart with LocalStorage
selivanov-d/thinknetica-react-basic pull request #8
Opened 2018-12-28 20:04 UTC by selivanov-d

2018-12-30 18:57 UTC, index01d requested changes

2018-12-30 18:57 UTC, index01d commented on src/js/actions/product.js
> +    endpoint: `${apiBase}/spaces/${spaceId}/entries`,
лучше бы базу по апи то унести в middleware, оставить здесь только /entries

2018-12-30 18:57 UTC, index01d commented on src/js/components/CartWidget/CartWidgetContainer.js
> +    loadCartContent();
на данном этапе стоит реализовать loadCartContent с помощью функции prepareData (как было в практике)

2018-12-30 18:57 UTC, index01d commented on src/js/components/CartWidget/CartWidgetContainer.js
> +    loadCartContent();
таким образом код получения необходимых для рендеринга страницы данных окажется в настройке роутов (нам это пригодится в дальнейшем для SSR)

2019-01-14 18:40 UTC, selivanov-d commented on src/js/actions/product.js
> +    endpoint: `${apiBase}/spaces/${spaceId}/entries`,
Кажется, уносить базу (https://cdn.contentful.com/spaces/.../entries) в middleware плохая идея. Ведь потенциально этот middleware может быть использован с любыми запросами к удалённому API.

2019-01-14 19:12 UTC, selivanov-d commented on src/js/components/CartWidget/CartWidgetContainer.js
> +    loadCartContent();
Поправил.

2019-01-15 21:22 UTC, index01d commented on src/js/actions/product.js
> +    endpoint: `${apiBase}/spaces/${spaceId}/entries`,
всегда есть вариант сделать специфичный middleware для конкретного api, тк другого в этой аппке сейчас не предвидится

2019-01-15 21:23 UTC, index01d approved these changes

2019-01-15 21:23 UTC, index01d commented on src/js/routes/IndexPageRoute.js
> +  prepareData: (store) => {
здесь в будущем нужно будет возвращать результат диспетчеризации в виде Promise от fetchProducts

2019-01-19 07:32 UTC, merged